# Generated by Django 3.1.1 on 2021-01-20 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20210120_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='code',
            field=models.CharField(default='SA', max_length=32),
            preserve_default=False,
        ),
    ]
